version: '3'

services:
  db:
    image: mysql:5.7
    command: 
      - --innodb-use-native-aio=0    
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
      - ./script:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=senha01
      - MYSQL_DATABASE=nodedb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=senha02
      - TZ=America/Sao_Paulo
    networks:
      - node-network
  app:
    build: 
      context: ./node
      dockerfile: Dockerfile.code
    container_name: app
    ## entrypoint: dockerize -wait tcp://db:3306 -timeout 60s node index.js
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    ## tty: true
    ## environment:
    ##   - TZ=America/Sao_Paulo
    ports: 
      - "3000:3000"
    depends_on:
      - db
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.code
    container_name: nginx
    networks:
      - node-network
    tty: true
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "8080:80"
    depends_on:
      - app
networks:
  node-network:
    driver: bridge